name: Feature Request
description: File a idea on how to increase the value.
title: "[FEATURE]: "
labels: ["feature", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        Is your request really a feature or aiming to fix a bug, then raise a BUG REPORT
